name: Build sing-box Docker Images
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag to build
        id: version
        run: |
          echo "latest=latest" >> $GITHUB_OUTPUT
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            echo "id=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "id=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout singbox
        run: |
          git clone -b ${{ steps.version.outputs.id }} --depth 1 https://github.com/SagerNet/sing-box.git
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/zengkid/sing-box
      # - name: Get tag to build
      #   id: tag
      #   run: |
      #     echo "latest=ghcr.io/sagernet/sing-box:latest" >> $GITHUB_OUTPUT
      #     if [[ -z "${{ github.event.inputs.tag }}" ]]; then
      #       echo "versioned=ghcr.io/sagernet/sing-box:${{ github.ref_name }}" >> $GITHUB_OUTPUT
      #     else
      #       echo "versioned=ghcr.io/sagernet/sing-box:${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
      #     fi
      - name: list files
        run: | 
          ls -l
      - name: Build and release Docker images
        uses: docker/build-push-action@v5
        with:
          platforms: linux/386,linux/amd64,linux/arm64,linux/s390x
          context: sing-box
          target: dist
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
          tags: |
            ghcr.io/zengkid/sing-box:${{ steps.version.outputs.latest }}
            ghcr.io/zengkid/sing-box:${{ steps.version.outputs.id }}
          push: true
